### ISSUE TITLE
Do not test respond_to

### ISSUE THREAD

**Issue by sam** [sam/doubleshot#16]
Changing a method-name would currently break the corresponding `must_respond_to` tests we have. This feels wrong since we're already testing the actual call and expected behavior of the method and those tests would break anyway.

So these tests aren't increasing coverage, they're not serving as documentation really, and they're not aiding in OOD. They're just a redundant artifact.

So let's remove them.

That's my thoughts anyways. @ckrailo?

**Comment by ckrailo** [comment]
K

On Sep 21, 2012, at 10:01 AM, Sam Smoot notifications@github.com wrote:

Changing a method-name would currently break the corresponding
must_respond_to tests we have. This feels wrong since we're already testing
the actual call and expected behavior of the method and those tests would
break anyway.

So these tests aren't increasing coverage, they're not serving as
documentation really, and they're not aiding in OOD. They're just a
redundant artifact.

So let's remove them.

That's my thoughts anyways. @ckrailo https://github.com/ckrailo?

—
Reply to this email directly or view it on
GitHubhttps://github.com/sam/doubleshot/issues/16.

**Comment by ckrailo** [comment]
Done
