### ISSUE TITLE
Add gemspec#valid? alias for validate.

### ISSUE THREAD

**Issue by ckrailo** [sam/doubleshot#25]
Makes code/tests prettier.

**Comment by sam** [comment]
I actually just added a Minitest matcher for `#must`. So the line is now:

``` ruby
config.gemspec.must :validate
```

Which I think is good enough.

I also modified `Minitest::Assertions#assert_predicate` so that if a matching method is not found, **but** the method with a "?" appended is, then the question-mark method is called. This lets us:

``` ruby
config.target.must :exist
```

Which executes `Pathname#exist?` since there is no `#exist` method.

I'm pretty happy with these tweaks. Don't see a need to monkey-patch `Gem::Specification` anymore. Feel free to re-open though if you'd like to discuss further.
