### ISSUE TITLE
Aether always adds Central

### ISSUE THREAD

**Issue by sam** [sam/doubleshot#64]
This seems wrong since we can't lock down repositories on TravisCI... but I'm not 100% confident.

The code I'm referencing is here: https://github.com/sam/doubleshot/blob/master/ext/java/Aether.java#L54-55

``` java
RemoteRepository central = new RemoteRepository( "central", "default", "http://repo1.maven.org/maven2/" );
repos.add(central);
```

If we decide to remove this, then I'm pretty sure it would just involve deleting those lines.

If it defaulted to Central when no other repository was specified (like Doubleshot does) that would be one thing, but it's actually adding it in the constructor, so you don't get the option of _not_ adding Central.

Thoughts?

**Comment by ckrailo** [comment]
I agree. Not necessary, so I fixed it.

**Comment by ckrailo** [comment]
I should have waited for Travis CI to come back with results.

We shouldn't exclude the other repos just because we're on Travis, so we should only have `if/end` and not `if/else/end`.

Travis doesn't have a complete mirror, so it still tried some things from repo1.maven.org and got errors. [Only 1 of the 3 Travis test runs had this happen.](https://travis-ci.org/#!/ckrailo/doubleshot/jobs/3022278)

**Comment by ckrailo** [comment]
@sam: Are any of the 3 non-Travis and non-Maven mirrors full mirrors? That's what we need.

**Comment by sam** [comment]
@ckrailo I'm not sure what you're asking. repo1 is Central. ibiblio is the main mirror for it.

I made the `if...end` change.

**Comment by ckrailo** [comment]
Ah, cool. Just making sure we have more than one complete mirror, since repo1.maven is unreliable. Close once you see it pass tests.
